replicaCount: 2

image:
  repository: ghcr.io/tonibyte/flask-app
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30080

nameOverride: flask-app
fullnameOverride: flask-app