apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-app.fullname" . }}
  labels:
    app: {{ include "flask-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "flask-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "flask-app.name" . }}
    spec:
      containers:
        - name: flask
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
                   env:
            - name: APP_MODE
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: APP_MODE

            - name: WELCOME_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: WELCOME_MESSAGE

            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: flask-db-secret
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: flask-db-secret
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: flask-db-secret
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: flask-db-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flask-db-secret
                  key: DB_PASSWORD

                  readinessProbe:
          httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 20